version: '3'
services:
  web:
    build: .
    ports:
      - "80:8080"
  db:
    image: "mysql"
    environment: 
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/test-db

volumes:
  db-data: